version: '2'
services:
# redis:
#   restart: always
#   container_name: telegram-bot-redis
#   image: redis:3.2

# mongo:
#   image: mongo:3.3
#   volumes:
#     - storage:/data/db

# db:
#   restart: always
#   ports:
#     - "5432:5432"
#   container_name: telegram-bot-postgres
#   build: docker/postgres
#   volumes:
#     - storage:/var/lib/postgresql/data
#   environment:
#     POSTGRES_USER: "${DB_USER}"
#     POSTGRES_PASSWORD: "${DB_PASSWORD}"
#     POSTGRES_DB: "${DB_NAME}"

  db:
    restart: always
    container_name: telegram-bot-mysql
    ports:
      - "3306:3306"
    build: docker/mysql
    volumes:
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - storage:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"

  nginx:
    restart: always
    container_name: telegram-bot-nginx
    image: nginx:latest
    ports:
      - "8200:80"
    volumes:
      - ./src:/src
      - ./logs/nginx/:/logs
      - ./docker/nginx/conf.d:/etc/nginx/conf.d/
    links:
     - php

  php:
    restart: always
    container_name: telegram-bot-php
    build: docker/php
    volumes:
      - ./src:/src
      - ./logs/php:/logs
    env_file:
      - ./.env

volumes:
  storage: